/** Данные для первичного наполнения сайта. Всё, что здесь записано, подтверждено документами федерации или прежними данными владельца. */

export const MUNICIPALITIES = [
  { slug: "alushta", name: "Алушта", kind: "city" },
  { slug: "armyansk", name: "Армянск", kind: "city" },
  { slug: "dzhankoy", name: "Джанкой", kind: "city" },
  { slug: "evpatoriya", name: "Евпатория", kind: "city" },
  { slug: "kerch", name: "Керчь", kind: "city" },
  { slug: "krasnoperekopsk", name: "Красноперекопск", kind: "city" },
  { slug: "saki", name: "Саки", kind: "city" },
  { slug: "simferopol", name: "Симферополь", kind: "city" },
  { slug: "sudak", name: "Судак", kind: "city" },
  { slug: "feodosiya", name: "Феодосия", kind: "city" },
  { slug: "yalta", name: "Ялта", kind: "city" },
  { slug: "bakhchisarayskiy", name: "Бахчисарайский район", kind: "district" },
  { slug: "belogorskiy", name: "Белогорский район", kind: "district" },
  { slug: "dzhankoyskiy", name: "Джанкойский район", kind: "district" },
  { slug: "kirovskiy", name: "Кировский район", kind: "district" },
  { slug: "krasnogvardeyskiy", name: "Красногвардейский район", kind: "district" },
  { slug: "krasnoperekopskiy", name: "Красноперекопский район", kind: "district" },
  { slug: "leninskiy", name: "Ленинский район", kind: "district" },
  { slug: "nizhnegorskiy", name: "Нижнегорский район", kind: "district" },
  { slug: "pervomayskiy", name: "Первомайский район", kind: "district" },
  { slug: "razdolnenskiy", name: "Раздольненский район", kind: "district" },
  { slug: "sakskiy", name: "Сакский район", kind: "district" },
  { slug: "simferopolskiy", name: "Симферопольский район", kind: "district" },
  { slug: "sovetskiy", name: "Советский район", kind: "district" },
  { slug: "chernomorskiy", name: "Черноморский район", kind: "district" },
  { slug: "sevastopol", name: "Севастополь", kind: "federal-city" },
] as const;

export const PEOPLE = [
  { id: "zhmakina", name: "Жмакина Виктория Николаевна", position: "Президент", group: "leadership", order: 1, city: "simferopol" },
  { id: "danilchenko", name: "Данильченко Юрий Леонидович", position: "Вице-президент, и. о. главного тренера сборной", group: "leadership", order: 2, city: "yalta" },
  { id: "dmitrieva", name: "Дмитриева Лариса Ивановна", position: "Представитель федерации", group: "representative", order: 10, city: "dzhankoy" },
  { id: "dyagovets", name: "Дяговец Марина Ованесовна", position: "Представитель федерации", group: "representative", order: 11, city: "feodosiya" },
] as const;

export const SECTIONS = [
  {
    title: "JDL",
    city: "simferopol",
    address: "ул. Балаклавская, 41, офис 118",
    coach: "Жмакина Виктория Николаевна",
    phone: "+7 978 738-32-46",
    messengerUrl: "https://vk.ru/jdl_crimea",
  },
  {
    title: "Волна",
    city: "feodosiya",
    address: "г. Феодосия",
    coach: "Дяговец Марина Ованесовна",
    phone: "+7 978 844-83-80",
    messengerUrl: "https://vk.ru/club240737297",
  },
  {
    title: "Драйвовая пружина",
    city: "dzhankoy",
    address: "г. Джанкой",
    coach: "Дмитриева Лариса Ивановна",
    phone: "+7 978 755-64-95",
    messengerUrl: "https://vk.ru/club240936471",
  },
] as const;

export const EVENTS = [
  {
    slug: "respublikanskie-sorevnovaniya-2026",
    title: "Республиканские соревнования",
    type: "competition",
    level: "republic",
    dateFrom: "2026-09-19",
    dateTo: "2026-09-19",
    city: "simferopol",
  },
  {
    slug: "kubok-kryma-2026",
    title: "Кубок Крыма",
    type: "competition",
    level: "republic",
    dateFrom: "2026-09-19",
    dateTo: "2026-09-19",
    city: "simferopol",
  },
  {
    slug: "kubok-rossii-2026",
    title: "Кубок России и всероссийские соревнования",
    type: "competition",
    level: "russia",
    dateFrom: "2026-11-13",
    dateTo: "2026-11-16",
    venue: "Москва",
  },
] as const;

type DocSeed = {
  file: string;
  title: string;
  category: "federation" | "rules" | "classification" | "regulations" | "education" | "orders" | "antidoping" | "forms";
  order: number;
  number?: string;
  date?: string;
  description?: string;
  status?: "current" | "archived";
  published: boolean;
};

const PERSONAL = "В документе есть персональные данные. Опубликуйте его только после проверки и при наличии согласий.";

export const DOCUMENTS: DocSeed[] = [
  {
    file: "ustav-oo-frsrk.pdf",
    title: "Устав Общественной организации «Федерация роуп скиппинга (спортивной скакалки) Республики Крым»",
    category: "federation",
    order: 10,
    date: "2023-12-16",
    description: "Утверждён учредительным собранием, протокол № 7 от 16 декабря 2023 года. Зарегистрирован Управлением Минюста России по Республике Крым 28 февраля 2024 года.",
    published: true,
  },
  {
    file: "svidetelstvo-registratsiya-nko.pdf",
    title: "Свидетельство о государственной регистрации некоммерческой организации",
    category: "federation",
    order: 15,
    date: "2024-03-13",
    description: "Выдано Управлением Министерства юстиции России по Республике Крым. Запись в ЕГРЮЛ внесена 5 марта 2024 года за основным государственным регистрационным номером 1249100003448.",
    published: true,
  },
  {
    file: "svidetelstvo-postanovka-na-uchet-nalog.pdf",
    title: "Свидетельство о постановке на учёт в налоговом органе",
    category: "federation",
    order: 16,
    date: "2024-03-05",
    description: "Выдано Межрайонной инспекцией Федеральной налоговой службы № 9 по Республике Крым. ИНН 9102295198, КПП 9102010001.",
    published: true,
  },
  {
    file: "prikaz-akkreditatsiya-242-od.pdf",
    title: "Приказ Министерства спорта Республики Крым о государственной аккредитации",
    category: "federation",
    order: 20,
    number: "242-ОД",
    date: "2024-04-22",
    description: "Аккредитация федерации по виду спорта «роуп скиппинг (спортивная скакалка)» сроком на три года со дня подписания приказа (пункт 2 приказа).",
    published: true,
  },
  {
    file: "uvedomlenie-akkreditatsiya-02-19-886.pdf",
    title: "Уведомление об аккредитации",
    category: "federation",
    order: 30,
    number: "02-19/886",
    date: "2024-04-27",
    published: true,
  },
  {
    file: "vypiska-reestr-vidov-sporta.pdf",
    title: "Выписка из Всероссийского реестра видов спорта: «роуп скиппинг (спортивная скакалка)»",
    category: "federation",
    order: 35,
    description: "Код вида спорта и спортивных дисциплин по Всероссийскому реестру видов спорта (ВРВС). Код вида спорта: 178 000 1 4 1 1 Я.",
    published: true,
  },
  {
    file: "pravila-vida-sporta-2024.pdf",
    title: "Правила вида спорта «роуп скиппинг (спортивная скакалка)»",
    category: "rules",
    order: 10,
    number: "264",
    date: "2022-03-29",
    description: "Утверждены приказом Минспорта России от 29 марта 2022 года № 264. Дисциплины, возрастные группы, судейство, антидопинговый контроль.",
    published: true,
  },
  {
    file: "polozhenie-sudejskie-kongressy-2024.pdf",
    title: "Положение о проведении судейских конгрессов Федерации роуп скиппинга России, 2024 год",
    category: "rules",
    order: 20,
    description: "Порядок региональных и всероссийских судейских конгрессов.",
    published: true,
  },
  {
    file: "ktss-sportivnye-sudji.xls",
    title: "Квалификационные требования к спортивным судьям (КТСС)",
    category: "rules",
    order: 30,
    description: "Требования к присвоению и подтверждению судейских категорий по виду спорта.",
    published: true,
  },
  {
    file: "kodeks-etiki-fssr-2026.pdf",
    title: "Кодекс этики Федерации спортивной скакалки (роуп скиппинга) России",
    category: "rules",
    order: 40,
    date: "2026-07-09",
    description: "Утверждён решением Правления ОФСОО «ФССР» 9 июля 2026 года. Обязанности спортсмена, тренера, спортивного и главного судьи, ответственность за нарушение.",
    published: true,
  },
  {
    file: "polozhenie-evsk-173-2025.pdf",
    title: "Положение о Единой всероссийской спортивной классификации",
    category: "classification",
    order: 10,
    number: "173",
    date: "2025-03-03",
    description: "Утверждено приказом Минспорта России от 3 марта 2025 года № 173. Порядок присвоения и подтверждения разрядов и званий. Проверяйте наличие изменений на сайте Минспорта России.",
    published: true,
  },
  {
    file: "evsk-299-2026.xls",
    title: "ЕВСК: нормы и требования по роуп скиппингу, редакция 2026 года",
    category: "classification",
    order: 20,
    description: "Таблица требований и условий выполнения для разрядов. Актуальность редакции проверяйте на сайте Минспорта России.",
    published: true,
  },
  {
    file: "programma-razvitiya-vida-sporta.pdf",
    title: "Программа развития вида спорта «роуп скиппинг (спортивная скакалка)» в Российской Федерации",
    category: "education",
    order: 10,
    number: "123",
    date: "2022-02-22",
    description: "Утверждена приказом Минспорта России № 123.",
    published: true,
  },
  {
    file: "obrazovatelnaya-programma-sportpodgotovki.pdf",
    title: "Примерная дополнительная образовательная программа спортивной подготовки",
    category: "education",
    order: 20,
    number: "1118",
    date: "2022-11-30",
    description: "Утверждена приказом Минспорта России от 30 ноября 2022 года № 1118, действует с 1 января 2023 года.",
    published: true,
  },
  {
    file: "federalnyj-standart-sportpodgotovki-905-2022.pdf",
    title: "Федеральный стандарт спортивной подготовки по виду спорта «роуп скиппинг (спортивная скакалка)»",
    category: "education",
    order: 30,
    number: "905",
    date: "2022-11-02",
    description: "Утверждён приказом Минспорта России от 2 ноября 2022 года № 905. Зарегистрирован Минюстом России 30 ноября 2022 года, регистрационный № 71220. Действует с 1 января 2023 года.",
    published: true,
  },
  {
    file: "prikaz-17-r-razryady-2024.pdf",
    title: "Приказ управления молодёжи, спорта и туризма администрации города Симферополя «О присвоении спортивных разрядов»",
    category: "orders",
    order: 10,
    number: "17-р",
    date: "2024-11-27",
    description: PERSONAL,
    published: false,
  },
  {
    file: "prikaz-3-s-sudejskaya-kategoriya.pdf",
    title: "Приказ управления молодёжи, спорта и туризма администрации города Симферополя «О присвоении квалификационной категории спортивных судей»",
    category: "orders",
    order: 20,
    number: "3-с",
    date: "2025-03-07",
    description: PERSONAL,
    published: false,
  },
  {
    file: "prikaz-13-s-sudejskaya-kategoriya.pdf",
    title: "Приказ № 13-с о присвоении квалификационной категории спортивного судьи",
    category: "orders",
    order: 30,
    number: "13-с",
    description: `${PERSONAL} Дату приказа укажите по оригиналу.`,
    published: false,
  },
  {
    file: "prikaz-2-s-sudejskaya-kategoriya.pdf",
    title: "Приказ № 2-с о присвоении судейской категории",
    category: "orders",
    order: 40,
    number: "2-с",
    date: "2025-02-14",
    description: PERSONAL,
    published: false,
  },
  {
    file: "prikaz-o-razryadah-2025.pdf",
    title: "Приказ о присвоении спортивных разрядов",
    category: "orders",
    order: 50,
    date: "2025-11-18",
    description: PERSONAL,
    published: false,
  },
  {
    file: "sbornaya-2025.pdf",
    title: "Состав сборной команды Республики Крым, 2025 год",
    category: "orders",
    order: 60,
    description: `${PERSONAL} В списке есть несовершеннолетние спортсмены.`,
    published: false,
  },
  {
    file: "sbornaya-2025-dopolnenie.pdf",
    title: "Дополнение к составу сборной команды Республики Крым, 2025 год",
    category: "orders",
    order: 70,
    description: `${PERSONAL} В списке есть несовершеннолетние спортсмены.`,
    published: false,
  },
  {
    file: "sbornaya-2026.pdf",
    title: "Состав сборной команды Республики Крым на 2026 год",
    category: "orders",
    order: 80,
    description: `${PERSONAL} В списке есть несовершеннолетние спортсмены.`,
    published: false,
  },
];

export const AUDIO: { file: string; title: string }[] = [
  { file: "30-sekund.mp3", title: "30 секунд" },
  { file: "60-sekund.mp3", title: "60 секунд" },
  { file: "90-sekund.mp3", title: "90 секунд" },
  { file: "120-sekund.mp3", title: "120 секунд" },
  { file: "180-sekund.mp3", title: "180 секунд" },
  { file: "skorost-2x30-sekund.mp3", title: "Скорость, 2 по 30 секунд" },
  { file: "sila-2x30-sekund.mp3", title: "Сила, 2 по 30 секунд" },
  { file: "pryzhki-4-cheloveka.mp3", title: "Прыжки, 4 человека" },
  { file: "pryzhki-2-skakalki-4-cheloveka.mp3", title: "Прыжки через 2 скакалки, 4 человека" },
  { file: "dvojnye-pryzhki.mp3", title: "Двойные прыжки" },
  { file: "trojnye-pryzhki.mp3", title: "Тройные прыжки" },
  { file: "pryzhki-2-skakalki-1-chelovek.mp3", title: "Прыжки через 2 скакалки, 1 человек" },
  { file: "pryzhki-2-skakalki-2-cheloveka.mp3", title: "Прыжки через 2 скакалки, 2 человека" },
  { file: "volnye-uprazhneniya.mp3", title: "Вольные упражнения" },
  { file: "volnye-uprazhneniya-gruppa.mp3", title: "Вольные упражнения, группа" },
  { file: "komandnye-sorevnovaniya.mp3", title: "Командные соревнования" },
];
