/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    'audio-tracks': AudioTrack;
    videos: Video;
    news: News;
    events: Event;
    municipalities: Municipality;
    sections: Section;
    people: Person;
    pages: Page;
    galleries: Gallery;
    'ranking-entries': RankingEntry;
    inquiries: Inquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'audio-tracks': AudioTracksSelect<false> | AudioTracksSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    municipalities: MunicipalitiesSelect<false> | MunicipalitiesSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    'ranking-entries': RankingEntriesSelect<false> | RankingEntriesSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Люди, которые могут входить в админку. Добавлять и удалять сотрудников может только администратор.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Первый созданный сотрудник всегда становится администратором. Остальным роль выбирает администратор.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Фотографии и картинки. Файлы хранятся на сервере (S3), а не внутри сайта.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Устав, приказы, положения, протоколы. Загрузите файл — он сохранится на сервере, а на сайте появится ссылка.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  category: 'federation' | 'rules' | 'classification' | 'regulations' | 'education' | 'orders' | 'antidoping' | 'forms';
  number?: string | null;
  docDate?: string | null;
  description?: string | null;
  status: 'current' | 'archived';
  order?: number | null;
  /**
   * Включите, когда документ проверен. Документы со списками детей публикуйте только при согласии родителей.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Официальные звуковые дорожки для дисциплин. Формат MP3, файлы хранятся на сервере.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio-tracks".
 */
export interface AudioTrack {
  id: number;
  title: string;
  durationLabel?: string | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Загрузите видеофайл (MP4) или вставьте ссылку на видео в VK Видео, Rutube или YouTube.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  externalUrl?: string | null;
  poster?: (number | null) | Media;
  date?: string | null;
  description?: string | null;
  published?: boolean | null;
  /**
   * Снимите, если видео нужно только для первого экрана главной.
   */
  inGallery?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Новости федерации. Чтобы новость появилась на сайте, включите «Показывать на сайте».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  slug?: string | null;
  publishedAt: string;
  excerpt: string;
  cover?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  event?: (number | null) | Event;
  featured?: boolean | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Соревнования, семинары, сборы. Статус («Предстоит», «Завершено») считается по датам сам. Протоколы добавляйте в блок «Документы мероприятия».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug?: string | null;
  type: 'competition' | 'festival' | 'seminar' | 'course' | 'camp' | 'other';
  level: 'municipal' | 'republic' | 'russia' | 'international';
  dateFrom: string;
  dateTo?: string | null;
  municipality?: (number | null) | Municipality;
  venue?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  registrationUrl?: string | null;
  registrationDeadline?: string | null;
  documents?:
    | {
        kind: 'regulation' | 'rules' | 'invitation' | 'start-protocol' | 'final-protocol' | 'photo-report' | 'other';
        document: number | Document;
        id?: string | null;
      }[]
    | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 25 муниципальных образований Республики Крым и Севастополь (город федерального значения, не входит в Республику Крым). Обычно менять их не нужно.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "municipalities".
 */
export interface Municipality {
  id: number;
  name: string;
  /**
   * Совпадает с кодом территории на карте Крыма. Не меняйте без необходимости.
   */
  slug?: string | null;
  kind: 'city' | 'district' | 'federal-city';
  representative?: (number | null) | Person;
  updatedAt: string;
  createdAt: string;
}
/**
 * Публикуйте данные людей только с их согласия. Фото детей — только с согласием родителей.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  position: string;
  group: 'leadership' | 'coach' | 'judge' | 'representative';
  photo?: (number | null) | Media;
  bio?: string | null;
  phone?: string | null;
  email?: string | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Места, где можно заниматься роуп скиппингом. Показываются на карте и в разделе «Найти секцию».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: number;
  title: string;
  municipality: number | Municipality;
  organization?: string | null;
  address: string;
  coach?: string | null;
  ageFrom?: number | null;
  ageTo?: number | null;
  schedule?: string | null;
  isFree?: boolean | null;
  priceNote?: string | null;
  disciplines?:
    | (
        | 'jumps-30'
        | 'jumps-180'
        | 'freestyle'
        | 'double-jumps'
        | 'triple-jumps'
        | 'jumps-4'
        | 'two-ropes-4'
        | 'freestyle-group'
        | 'two-ropes-1'
        | 'two-ropes-2'
        | 'team'
      )[]
    | null;
  phone?: string | null;
  messengerUrl?: string | null;
  description?: string | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Тексты разделов: «О федерации», «Родителям», «Антидопинг», политика персональных данных. Пока текст пустой, на сайте написано, что раздел в разработке.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  key:
    | 'about'
    | 'history'
    | 'parents'
    | 'antidoping'
    | 'rules'
    | 'education-judges'
    | 'education-coaches'
    | 'leadership'
    | 'privacy'
    | 'cookies'
    | 'media';
  lead?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Фотографии с соревнований и мероприятий. Фото детей публикуйте только с согласия родителей.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  title: string;
  slug?: string | null;
  date: string;
  description?: string | null;
  cover?: (number | null) | Media;
  event?: (number | null) | Event;
  photos?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Каждая строка это один спортсмен в одной дисциплине и возрастной группе за сезон. Места на сайте считаются сами по очкам. Публикуйте данные спортсменов, в том числе детей, только с согласия родителей.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ranking-entries".
 */
export interface RankingEntry {
  id: number;
  athlete: string;
  season: string;
  discipline:
    | 'jumps-30'
    | 'jumps-180'
    | 'freestyle'
    | 'double-jumps'
    | 'triple-jumps'
    | 'jumps-4'
    | 'two-ropes-4'
    | 'freestyle-group'
    | 'two-ropes-1'
    | 'two-ropes-2'
    | 'team';
  ageGroup: '10-11' | '12-14' | '15-17' | '18+';
  gender: 'female' | 'male';
  municipality?: (number | null) | Municipality;
  club?: string | null;
  points: number;
  starts?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Сообщения, которые посетители отправили через форму на странице «Контакты». Содержат персональные данные: не выгружайте и не пересылайте их без необходимости.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  topic: 'general' | 'join-club' | 'join-coach' | 'join-judge' | 'press';
  email?: string | null;
  phone?: string | null;
  message: string;
  consent: boolean;
  status: 'new' | 'done';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'audio-tracks';
        value: number | AudioTrack;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'municipalities';
        value: number | Municipality;
      } | null)
    | ({
        relationTo: 'sections';
        value: number | Section;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'ranking-entries';
        value: number | RankingEntry;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  number?: T;
  docDate?: T;
  description?: T;
  status?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio-tracks_select".
 */
export interface AudioTracksSelect<T extends boolean = true> {
  title?: T;
  durationLabel?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  externalUrl?: T;
  poster?: T;
  date?: T;
  description?: T;
  published?: T;
  inGallery?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  excerpt?: T;
  cover?: T;
  body?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  event?: T;
  featured?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  level?: T;
  dateFrom?: T;
  dateTo?: T;
  municipality?: T;
  venue?: T;
  description?: T;
  registrationUrl?: T;
  registrationDeadline?: T;
  documents?:
    | T
    | {
        kind?: T;
        document?: T;
        id?: T;
      };
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "municipalities_select".
 */
export interface MunicipalitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  representative?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  title?: T;
  municipality?: T;
  organization?: T;
  address?: T;
  coach?: T;
  ageFrom?: T;
  ageTo?: T;
  schedule?: T;
  isFree?: T;
  priceNote?: T;
  disciplines?: T;
  phone?: T;
  messengerUrl?: T;
  description?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  group?: T;
  photo?: T;
  bio?: T;
  phone?: T;
  email?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  key?: T;
  lead?: T;
  body?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  description?: T;
  cover?: T;
  event?: T;
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ranking-entries_select".
 */
export interface RankingEntriesSelect<T extends boolean = true> {
  athlete?: T;
  season?: T;
  discipline?: T;
  ageGroup?: T;
  gender?: T;
  municipality?: T;
  club?: T;
  points?: T;
  starts?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  topic?: T;
  email?: T;
  phone?: T;
  message?: T;
  consent?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Название, контакты, реквизиты и ссылки. Они выводятся в шапке, подвале, на странице «Контакты» и в документах.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  fullName: string;
  shortName: string;
  legalName?: string | null;
  description?: string | null;
  /**
   * Она же остаётся запасной, пока грузится видео, и стоит на тёмных полосах внутренних страниц.
   */
  heroImage?: (number | null) | Media;
  heroMode?: ('photo' | 'video') | null;
  /**
   * Выберите видео из раздела «Содержимое → Видео» (загруженный файл MP4, у которого включено «Показывать на сайте»). Лучше ролик 10–20 секунд, 1920×1080, до 8 МБ. Звука на сайте нет. Хотите скрыть его из раздела «Медиа», снимите у самого видео галочку «Показывать в разделе Медиа».
   */
  heroVideo?: (number | null) | Video;
  /**
   * По умолчанию на телефонах показывается фото, чтобы не тратить мобильный трафик посетителей.
   */
  heroVideoMobile?: boolean | null;
  ogImage?: (number | null) | Media;
  banners?: {
    /**
     * Показывается везде, где у раздела ниже нет своей картинки. Если пусто, берётся главная картинка первого экрана.
     */
    default?: (number | null) | Media;
    calendar?: (number | null) | Media;
    documents?: (number | null) | Media;
    news?: (number | null) | Media;
    media?: (number | null) | Media;
    sections?: (number | null) | Media;
    contacts?: (number | null) | Media;
    participants?: (number | null) | Media;
    about?: (number | null) | Media;
  };
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  vk?: string | null;
  telegram?: string | null;
  ogrn?: string | null;
  inn?: string | null;
  kpp?: string | null;
  bankDetails?: string | null;
  accreditation?: {
    orderNumber?: string | null;
    orderDate?: string | null;
    issuedBy?: string | null;
    term?: string | null;
    vrvsCode?: string | null;
  };
  metrikaId?: string | null;
  notifyEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  fullName?: T;
  shortName?: T;
  legalName?: T;
  description?: T;
  heroImage?: T;
  heroMode?: T;
  heroVideo?: T;
  heroVideoMobile?: T;
  ogImage?: T;
  banners?:
    | T
    | {
        default?: T;
        calendar?: T;
        documents?: T;
        news?: T;
        media?: T;
        sections?: T;
        contacts?: T;
        participants?: T;
        about?: T;
      };
  phone?: T;
  email?: T;
  address?: T;
  vk?: T;
  telegram?: T;
  ogrn?: T;
  inn?: T;
  kpp?: T;
  bankDetails?: T;
  accreditation?:
    | T
    | {
        orderNumber?: T;
        orderDate?: T;
        issuedBy?: T;
        term?: T;
        vrvsCode?: T;
      };
  metrikaId?: T;
  notifyEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}